DROP TABLE users CASCADE CONSTRAINTS;

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  password VARCHAR2(255) NOT NULL,
  role VARCHAR2(50) CHECK (role IN ('organizer', 'participant')) NOT NULL,
  CONSTRAINT unique_email_role UNIQUE (email, role)
);

select * from users;