DROP TABLE events CASCADE CONSTRAINTS;

CREATE TABLE events (
  event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_title VARCHAR2(255) NOT NULL,
  event_description CLOB,
  event_organizer_id NUMBER NOT NULL,
  event_start_date DATE NOT NULL,
  event_start_time VARCHAR2(20) NOT NULL,
  event_end_time VARCHAR2(20) NOT NULL,
  event_location VARCHAR2(255),
  event_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (event_organizer_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);

select * from events;