DROP table feedback CASCADE CONSTRAINTS;

CREATE TABLE feedback (
  feedback_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  comment_text VARCHAR2(1000) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (event_id)
    REFERENCES events(event_id)
    ON DELETE CASCADE,
  FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE   -- ← optional: clean up feedback when a user is removed
);

select * from feedback;